version: '3'

services:
  container1:
    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
      - ./:/home/workdir/app
    command: /bin/sh
    working_dir: /home/workdir/app
    tty: true